#! /bin/bash

set -e

rm -f comp_comm.sh

cargo build --release
touch src/lib_fillin.rs

compiler_comm=`cargo build --release -v |  grep -Po 'Running \`\K[^\`]*' | sed -e 's/fillin/$1/g'`

echo "#! /bin/bash"  >> comp_comm.sh
echo "set -e"        >> comp_comm.sh
echo $compiler_comm >> comp_comm.sh

chmod u+x comp_comm.sh
