#! /bin/bash

set -e

SCRIPT=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)/$(basename -- "$0")")
SCRIPTPATH=`dirname $SCRIPT`

rm -f comp_comm.sh

cargo build -q --release
touch src/lib_fillin.rs


compiler_comm=`cargo build --release -v | grep -Po 'Running \`\K[^\`]*' | sed -e 's/fillin/$1/g' | sed 's#src/lib_#${SCRIPTPATH}/src/lib_#g'`

echo "#! /bin/bash"  >> comp_comm.sh
echo "set -e"        >> comp_comm.sh
echo "SCRIPTPATH=${SCRIPTPATH}" >> comp_comm.sh
echo $compiler_comm >> comp_comm.sh

chmod u+x comp_comm.sh
